version: 2
jobs: 
  build: 
    branches: 
      only: 
        - develop
    docker: 
      - image: "circleci/python:3.6"
    working_directory: ~/telegram-dogecoin
    steps: 
      - checkout
      - run:
          name: "install dependencies"
          command: |
            pip3 install block-io --user
            pip3 install requests --user
            pip3 install behave  --user
      - run:
          name: "run tests"
          command: behave
