version: 2
jobs: 
  build: 
    #branches:
    #  only:
    #    - develop
    docker: 
      - image: "circleci/python:3.6"
    working_directory: ~/telegram-dogecoin
    steps: 
      - checkout
      - run:
          name: "install dependencies"
          command: |
            pipenv install
      - run:
          name: "run behave tests"
          command: pipenv run behave
      - run:
          name: "run unit tests"
          command: pipenv run python3 -m unittest
